---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authz-envoy-config
    files:
      - envoy.yaml=./envoy.yaml
      - identity_sds.yaml=./identity_sds.yaml
      - ca_sds.yaml=./ca_sds.yaml
