---
apiVersion: v1
kind: Service
metadata:
  name: authorization-envoy
  labels:
    app: authorization-envoy
spec:
  type: ClusterIP
  selector:
    app: authorization-envoy
  ports:
    - name: http
      port: 80
      targetPort: http
